### ISSUE TITLE
Outdate Info

### ISSUE THREAD

**Issue by JoseAntonioBarriga** [MicrosoftDocs/powerapps-docs.es-es#8]
This is an excellent paper. Really good. Unfortunately is outdated.  Please update it.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 0f886011-a79a-8fa9-bb7c-f0adbb61b8d3
* Version Independent ID: 997f29d5-e836-fc31-647e-eb6a916afae4
* Content: [Descripción de las tarjetas de datos - Power Apps](https://docs.microsoft.com/es-es/powerapps/maker/canvas-apps/working-with-cards#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-cards.md](https://github.com/MicrosoftDocs/powerapps-docs.es-es/blob/live/powerapps-docs/maker/canvas-apps/working-with-cards.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by srvbpigh** [comment]
Hello, @JoseAntonioBarriga
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @JoseAntonioBarriga 

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by JoseAntonioBarriga** [comment]
Hi Cecilia

Of course.!  What I meant regarding updating was that some information published in this Power App documentation is outdated, for example, https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-cards. This page is part of a complete Power App Tutorial

As you can verify, that doc was updated three years ago (4/26/2016). Maybe that date is wrong, but if you go through all the screens, there are outdate. Let point that this documentation is excellent, so it is a pity that such a work has left behind. Power Apps I something that is evolving every date, so updating documentation is essential so that everybody will be able to use the new feature.

Looking forward,

José Antonio Barriga

**Comment by srvbpigh** [comment]
Hello, @JoseAntonioBarriga, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerapps-docs/issues/1391. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
